/* tasks.c — concrete tasks and the schedule.
 *
 *   task_equalize : fixed-point RX FFE over a block of post-ADC samples
 *                   (taps + stimulus baked in by the bridge from the sim).
 *   task_heartbeat: liveness print once per second.
 *
 * Budgets/block size are tunables; set EQ_BUDGET from a measured WCET.
 */
#include "bare.h"
#include "scheduler.h"
#include "tasks.h"
#include "serdes_workload.h"     /* generated by: bridge gen <s4p>  */
#include "eq_fixed.h"

/* ── tunables ─────────────────────────────────────────────────────────── */
#define FRAME_HZ      1000u      /* minor-cycle rate                        */
#define RUN_SECONDS   5u         /* 0 = run forever                         */
#ifndef EQ_BLOCK
#define EQ_BLOCK      256u       /* samples processed per equalize call     */
#endif
#ifndef EQ_BUDGET
#define EQ_BUDGET     52000u     /* WCET budget (cyc); measure on your CPU   */
#endif
#define HB_BUDGET     20000u

/* ── equalizer task ───────────────────────────────────────────────────── */
static eq_state_t eq_state;
static uint32_t   eq_pos;
volatile uint32_t eq_sink;       /* observable sink: defeats dead-code elim */

static void task_equalize(void){
    uint32_t p = eq_pos;
    int32_t  acc = 0;
    for(uint32_t i = 0; i < EQ_BLOCK; i++){
        int16_t y = eq_ffe_step(&eq_state, eq_ffe_taps, eq_stimulus[p]);
        acc += eq_slice(y);
        if(++p >= EQ_NSTIM) p = 0;
    }
    eq_pos   = p;
    eq_sink += (uint32_t)acc;
}

/* ── heartbeat task ───────────────────────────────────────────────────── */
static void task_heartbeat(void){
    uint32_t t = scheduler_ticks();
    if((t % FRAME_HZ) == 0){ uputs("alive "); uputd(t / FRAME_HZ); uputs("s\n"); }
}

/* ── schedule: major cycle of 3 frames (A, A, B) ──────────────────────── */
static const work_item_t frame_a[] = {
    { task_equalize,  EQ_BUDGET, "equalize"  },
    { task_heartbeat, HB_BUDGET, "heartbeat" },
};
static const work_item_t frame_b[] = {
    { task_equalize,  EQ_BUDGET, "equalize"  },
};
static const frame_t frames[] = {
    { frame_a, 2 },
    { frame_b, 1 },
};
static const schedule_t schedule = {
    frames, 2, FRAME_HZ, RUN_SECONDS
};

const schedule_t *tasks_schedule(void){ return &schedule; }
