/* bridge_cosim.c — validate the firmware's fixed-point datapath against a
 * floating-point reference, using the SAME taps + stimulus the Duo compiles.
 *
 * Build (after 'bridge gen' has produced tasks/serdes_workload.h):
 *   gcc -O2 -I../tasks -o cosim bridge_cosim.c -lm
 *   ./cosim
 */
#include <stdio.h>
#include <math.h>
#include <stdint.h>

#include "serdes_workload.h"   /* generated by: bridge gen <s4p> */
#include "eq_fixed.h"          /* the firmware kernel            */

int main(void)
{
    eq_state_t st; eq_reset(&st);
    double rb[EQ_FFE_LEN] = {0};
    double tap_f[EQ_FFE_LEN];
    for(int k=0;k<EQ_FFE_LEN;k++) tap_f[k] = eq_ffe_taps[k] / (double)(1 << EQ_TAP_Q);

    long   mism = 0, sat = 0;
    double se = 0, sig = 0;
    for(int n=0;n<EQ_NSTIM;n++){
        double x = eq_stimulus[n] / (double)(1 << EQ_SAMP_Q);
        for(int i=EQ_FFE_LEN-1;i>0;i--) rb[i]=rb[i-1];
        rb[0]=x;

        double yf=0;                          /* float reference     */
        for(int k=0;k<EQ_FFE_LEN;k++) yf += tap_f[k]*rb[k];

        int16_t yq  = eq_ffe_step(&st, eq_ffe_taps, eq_stimulus[n]);  /* fixed */
        double  yqf = yq / (double)(1 << EQ_SAMP_Q);

        if(((yf<0)?-1:1) != eq_slice(yq)) mism++;     /* slicer decision   */
        if(fabs(yf) >= 0.999){ sat++; continue; }     /* Q15 out-of-range  */
        double d = yf - yqf; se += d*d; sig += yf*yf; /* SNR where in-range */
    }
    double snr = 10.0*log10(sig/(se+1e-30));
    printf("cosim: %d samples  decision_mismatches=%ld  "
           "quant_SNR(in-range)=%.1f dB  saturated=%.1f%%\n",
           EQ_NSTIM, mism, snr, 100.0*sat/EQ_NSTIM);
    /* The datapath ends in a slicer, so correctness == decisions agree.
     * Output saturation just means |FFE out| can exceed 1.0 (expected). */
    printf("  -> fixed-point port %s the floating-point design"
           " (slicer decisions).\n", (mism==0) ? "MATCHES" : "DIVERGES from");
    return 0;
}
