/* bridge.c — host mediator. Build:
 *   gcc -O2 -I../simulation -I../tasks -o bridge \
 *       bridge.c ../simulation/s4p_channel.c -lm
 *
 *   ./bridge gen ../simulation/<file>.s4p ../tasks/serdes_workload.h 2048
 *   ./bridge cosim
 */
#include "serdes_sim.h"     /* OSF, FS, RX_FFE_LEN, ADC_BITS, MAX_CHANNEL_TAPS, CTLE */
#include "s4p_channel.h"
#include "bridge.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define SAMP_Q 15
#define TAP_Q  14

/* ── small DSP helpers (host-only) ───────────────────────────────────── */
static void butter1_hp(double Wn,double b[2],double a[2]){
    double C=1.0/tan(M_PI*Wn/2.0),D=1.0+C;
    b[0]=C/D; b[1]=-C/D; a[0]=1.0; a[1]=(1.0-C)/D;
}
static void butter2_lp(double Wn,double b[3],double a[3]){
    double C=1.0/tan(M_PI*Wn/2.0),C2=C*C,S2=sqrt(2.0),D=C2+S2*C+1.0;
    b[0]=1.0/D; b[1]=2.0/D; b[2]=1.0/D;
    a[0]=1.0; a[1]=2.0*(1.0-C2)/D; a[2]=(C2-S2*C+1.0)/D;
}
static void ctle_init(CTLE*c,double Fs,double z,double p,double A){
    double wh=z/(Fs/2.0),wl=p/(Fs/2.0);
    if(wh<=0){wh=1e-12;} if(wh>=1){wh=1-1e-12;}
    if(wl<=0){wl=1e-12;} if(wl>=1){wl=1-1e-12;}
    butter1_hp(wh,c->bhp,c->ahp); butter2_lp(wl,c->blp,c->alp);
    c->A=A; c->zi_hp[0]=c->zi_lp[0]=c->zi_lp[1]=0.0;
}
static double ctle_run(CTLE*c,double x){
    double hp=c->bhp[0]*x+c->zi_hp[0];
    c->zi_hp[0]=c->bhp[1]*x-c->ahp[1]*hp;
    double v=x+c->A*hp;
    double y=c->blp[0]*v+c->zi_lp[0];
    c->zi_lp[0]=c->blp[1]*v-c->alp[1]*y+c->zi_lp[1];
    c->zi_lp[1]=c->blp[2]*v-c->alp[2]*y;
    return y;
}
static double adc_q(double x,int B){
    if(x>1.0)x=1.0; if(x<-1.0)x=-1.0;
    int lv=1<<B; int xq=(int)round((x+1.0)*(lv-1)/2.0);
    return xq*2.0/(lv-1)-1.0;
}
static int q_round(double x,int qb,int lo,int hi){
    long v=lrint(x*(double)(1<<qb));
    if(v<lo)v=lo; if(v>hi)v=hi; return (int)v;
}

/* ── shared: build channel, stimulus, and trained FFE taps ───────────── */
typedef struct {
    double  ffe[RX_FFE_LEN];
    double *stream; int NS;     /* post-ADC samples */
    int     ph, pks;            /* decision phase, cursor sample offset */
} WorkSet;

static int build_workset(const char *s4p, WorkSet *w)
{
    static double h[MAX_CHANNEL_TAPS];
    S4pOpts o; s4p_default_opts(&o); o.verbose = 1;
    int L = channel_from_s4p(s4p, h, MAX_CHANNEL_TAPS, FS, &o);
    if(L <= 0) return -1;

    int NSYM = 6000, NS = NSYM*OSF;
    srand(12345);
    double *sym = malloc(NSYM*sizeof(double));
    double *stream = malloc(NS*sizeof(double));
    for(int i=0;i<NSYM;i++) sym[i] = (rand()&1)? 1.0 : -1.0;

    CTLE ctle; ctle_init(&ctle, FS, 50e9, 100e9, 1.6667);
    double *cbuf = calloc(L,sizeof(double));
    for(int pt=0;pt<NS;pt++){
        memmove(cbuf+1,cbuf,(L-1)*sizeof(double));
        cbuf[0]=sym[pt/OSF];
        double pc=0; for(int k=0;k<L;k++) pc+=h[k]*cbuf[k];
        pc=ctle_run(&ctle,pc);
        stream[pt]=adc_q(pc,ADC_BITS);
    }
    free(cbuf);

    /* isolated-symbol probe -> decision phase + cursor delay */
    double *p=calloc(L,sizeof(double));
    CTLE c2; ctle_init(&c2,FS,50e9,100e9,1.6667);
    int PN=4*OSF+L, pk=0; double pkv=0;
    for(int pt=0;pt<PN;pt++){
        memmove(p+1,p,(L-1)*sizeof(double));
        p[0]=(pt<OSF)?1.0:0.0;
        double pc=0; for(int k=0;k<L;k++) pc+=h[k]*p[k];
        pc=ctle_run(&c2,pc);
        if(fabs(pc)>pkv){pkv=fabs(pc);pk=pt;}
    }
    free(p);
    w->ph=pk%OSF; w->pks=pk;

    /* LMS train RX FFE */
    double ffe[RX_FFE_LEN]; memset(ffe,0,sizeof ffe); ffe[RX_FFE_PRE]=1.0;
    double *rb=calloc(RX_FFE_LEN,sizeof(double));
    double mu=0.01, erms=0; int nupd=0;
    for(int pt=0;pt<NS;pt++){
        memmove(rb+1,rb,(RX_FFE_LEN-1)*sizeof(double));
        rb[0]=stream[pt];
        if(pt%OSF==w->ph && pt-w->pks>=0){
            int m=(pt-w->pks)/OSF;
            if(m>=0 && m<NSYM){
                double y=0; for(int k=0;k<RX_FFE_LEN;k++) y+=ffe[k]*rb[k];
                double e=sym[m]-y;
                for(int k=0;k<RX_FFE_LEN;k++) ffe[k]+=mu*e*rb[k];
                erms+=e*e; nupd++;
            }
        }
    }
    free(rb);
    memcpy(w->ffe, ffe, sizeof ffe);
    w->stream=stream; w->NS=NS;
    printf("bridge: phase=%d cursor=%d, FFE trained over %d sym, rms err ~%.3f\n",
           w->ph, w->pks, nupd, nupd? sqrt(erms/nupd):0.0);
    free(sym);
    return 0;
}

/* ── mode: gen ───────────────────────────────────────────────────────── */
int bridge_gen(const char *s4p, const char *out, int n_export)
{
    WorkSet w;
    if(build_workset(s4p,&w)<0) return 1;

    int start = 64*OSF;
    if(n_export > w.NS) n_export = w.NS;
    if(start + n_export > w.NS) start = 0;

    FILE *fp=fopen(out,"w");
    if(!fp){ fprintf(stderr,"cannot write %s\n",out); free(w.stream); return 1; }
    fprintf(fp,
        "/* serdes_workload.h — AUTO-GENERATED by bridge from\n *   %s\n"
        " * Fixed-point firmware data. Regenerate; do not hand-edit. */\n"
        "#ifndef SERDES_WORKLOAD_H\n#define SERDES_WORKLOAD_H\n#include <stdint.h>\n\n",
        s4p);
    fprintf(fp,"#define EQ_FFE_LEN %d\n",RX_FFE_LEN);
    fprintf(fp,"#define EQ_TAP_Q   %d\n",TAP_Q);
    fprintf(fp,"#define EQ_SAMP_Q  %d\n",SAMP_Q);
    fprintf(fp,"#define EQ_NSTIM   %d\n\n",n_export);
    fprintf(fp,"static const int16_t eq_ffe_taps[EQ_FFE_LEN] = {\n  ");
    for(int k=0;k<RX_FFE_LEN;k++){
        fprintf(fp,"%6d,",q_round(w.ffe[k],TAP_Q,-32768,32767));
        if((k%8)==7) fprintf(fp,"\n  ");
    }
    fprintf(fp,"\n};\n\nstatic const int16_t eq_stimulus[EQ_NSTIM] = {\n  ");
    for(int i=0;i<n_export;i++){
        fprintf(fp,"%6d,",q_round(w.stream[start+i],SAMP_Q,-32768,32767));
        if((i%12)==11) fprintf(fp,"\n  ");
    }
    fprintf(fp,"\n};\n\n#endif /* SERDES_WORKLOAD_H */\n");
    fclose(fp);
    printf("bridge gen: wrote %s (EQ_FFE_LEN=%d, EQ_NSTIM=%d)\n",
           out, RX_FFE_LEN, n_export);
    free(w.stream);
    return 0;
}

int main(int argc, char **argv)
{
    if(argc>=2 && !strcmp(argv[1],"gen")){
        if(argc<3){ fprintf(stderr,"usage: bridge gen <s4p> [out.h] [n]\n"); return 1; }
        const char *out = (argc>=4)? argv[3] : "../tasks/serdes_workload.h";
        int n = (argc>=5)? atoi(argv[4]) : 2048;
        return bridge_gen(argv[2], out, n);
    }
    fprintf(stderr,"usage: bridge gen <file.s4p> [out.h] [n_export]\n"
                   "       (cosim is a separate binary; see Makefile)\n");
    return 1;
}
